live_config_reload = true
import = [
        "~/.config/alacritty/themes/themes/Cobalt2.toml"
]

[colors.primary]
background = "#000918"

[cursor]
blink_interval = 400
unfocused_hollow = false

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
TERM = "alacritty"

[font]
size = 14

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "FiraCode Nerd Font"

[font.offset]
x = 0
y = 1

[scrolling]
history = 10000

[window]
dynamic_title = true
opacity = 0.8

[window.dimensions]
columns = 90
lines = 30

[window.padding]
x = 5
y = 0

[shell]
program = "/bin/zsh"
args = ["-l","-c",'tmux a -t default || tmux new -s default\; source ~/.config/tmux/default.session.conf']